easy_admin:
  site_name: "Administration"
  formats:
    date: "d/m/Y"
    time: "H:i"
    datetime: "d/m/Y H:i:s"
  entities:
    # List the entity class name you want to manage

    # TOPIC
    Topic:
      class: App\Entity\Topic
      form:
        fields:
          - { property: "title", label: "Titre" }
          - { property: "content", label: "Commentaire" }
          - { property: "author", label: "Auteur" }
          - { property: "category", label: "Catégorie" }
          - { property: "subcategory", label: "Sous-catégorie" }

      list:
        max_results: 20
        fields:
          - { property: "title", label: "Titre" }
          - { property: "content", label: "Commentaire" }
          - { property: "author", label: "Auteur" }
          - { property: "category", label: "Catégorie" }
          - { property: "subcategory", label: "Sous-catégorie" }
          - { property: "featured", label: "Mis en avant ?" }
          - { property: "isActive", label: "Actif ?" }

    # COMMENT
    Comment:
      class: App\Entity\Comment
      form:
        fields:
          - { property: "topic", label: "Topic" }
          - { property: "content", label: "Commentaire" }
          - { property: "author", label: "Auteur" }

      list:
        max_results: 20
        fields:
          - { property: "topic", label: "Topic" }
          - { property: "content", label: "Commentaire" }
          - { property: "author", label: "Auteur" }

    # CATEGORY
    Category:
      class: App\Entity\Category
      form:
        fields:
          - { property: "name", label: "Nom de la catégorie" }

      list:
        max_results: 20
        fields:
          - { property: "name", label: "Nom de la catégorie" }

    # SUB CATEGORY
    SubCategory:
      class: App\Entity\SubCategory
      form:
        fields:
          - { property: "name", label: "Nom de la sous-catégorie" }
          - { property: "category", label: "Associé à la catégorie" }

      list:
        max_results: 20
        fields:
          - { property: "name", label: "Nom de la sous-catégorie" }
          - { property: "category", label: "Associé à la catégorie" }

    # USER
    User:
      class: App\Entity\User
      form:
        fields:
          - { property: "username", label: "Pseudo" }
          - { property: "avatar", label: "Avatar" }
          - { property: "name", label: "Prénom" }
          - { property: "lastname", label: "Nom" }
          - { property: "email", label: "Email" }
          - { property: "password", label: "Mot de passe" }

          - property: "roles"
            label: "Role supplémentaire"
            type: choice
            type_options:
              mapped: true
              expanded: false
              multiple: true
              choices:
                { "Administrateur": "ROLE_ADMIN", "Modérateur": "ROLE_MODO" }

          - property: "gender"
            type: choice
            type_options:
              mapped: true
              expanded: false
              multiple: false
              choices: { "Homme": "man", "Femme": "wooman", "Autre": "other" }

      list:
        max_results: 20
        fields:
          - { property: "username", label: "Pseudo" }
          - { property: "name", label: "Prénom" }
          - { property: "lastname", label: "Nom" }
          - { property: "email", label: "Email" }
          - { property: "isActive", label: "Actif ?" }
          - { property: "isBlocked", label: "Bloqué ?" }
          - { property: "roles", label: "Role" }

    # POKEMON
    Pokemon:
      class: App\Entity\Pokemon
      form:
        fields:
          - { property: "idPokemon", label: "Numéro d'identification" }
          - { property: "name", label: "Nom du pokemon" }
          - { property: "difficulty", label: "Difficulté" }

      list:
        max_results: 20
        fields:
          - { property: "idPokemon", label: "Numéro d'identification" }
          - { property: "name", label: "Nom du pokemon" }
          - { property: "difficulty", label: "Difficulté" }

    # BADGE
    Badge:
      class: App\Entity\Badge
      form:
        fields:
          - { property: "name", label: "Nom du badge" }
          - { property: "image", label: "Image" }

      list:
        max_results: 20
        fields:
          - { property: "name", label: "Nom du badge" }
          - { property: "image", label: "Image" }
